### ISSUE TITLE
TypeErrror on response

### ISSUE THREAD

**Issue by jakubd** [passivetotal/python_api#1]
On a fresh install of passivetotal api through pip.  I set up my API key and if I follow the docs and do:

```
pt-client pdns --query www.passivetotal.org --sources=pingly --format=table
```

I get:
```
Traceback (most recent call last):
  File "/usr/local/bin/pt-client", line 9, in <module>
    load_entry_point('passivetotal==1.0.17', 'console_scripts', 'pt-client')()
  File "/usr/local/lib/python2.7/dist-packages/passivetotal/cli/client.py", line 297, in main
    data = call_dns(args)
  File "/usr/local/lib/python2.7/dist-packages/passivetotal/cli/client.py", line 40, in call_dns
    data = client.get_passive_dns(**pruned)
  File "/usr/local/lib/python2.7/dist-packages/passivetotal/libs/dns.py", line 49, in get_passive_dns
    return self._get('dns', 'passive', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/passivetotal/api.py", line 134, in _get
    return self._json(response)
  File "/usr/local/lib/python2.7/dist-packages/passivetotal/api.py", line 106, in _json
    return response.json()
TypeError: 'dict' object is not callable
```

If I knock off the brackets I on line 106 in api.py I get a proper response:

```
 $ pt-client pdns --query www.passivetotal.org --sources=pingly --format=table
firstSeen            lastSeen             recordHash                                                        resolve          source
-------------------  -------------------  ----------------------------------------------------------------  ---------------  --------
2016-02-17 15:52:25  2016-02-17 15:52:25  70f448caf58c982848c95cba197999e5e8d7652691f6141cc886ed6f5fa03400  54.153.123.93    pingly
2016-02-16 14:37:21  2016-02-17 15:52:25  1b425c9919b03af9d12325e1be053da76c01664bcf31e0edb74f8bd52142be36  52.8.228.23      pingly
2016-02-13 17:52:19  2016-02-16 14:37:21  66dfd0be1f924e1ba8620d7184c2fae478ff1df84dd9201493a9a04c215b4da2  54.153.123.93    pingly
2016-02-13 17:52:19  2016-02-13 17:52:19  b8d8876db7621db15c0408170cb9a74098e422b723a66b0f15bac6fee4049deb  52.8.228.23      pingly
2016-02-08 15:23:00  2016-02-08 15:23:00  3ac592b0a2afcb786bc0bd92b1cdf8793e84b20db3b214ce3157e02837a8e938  54.153.123.93    pingly
2016-02-08 15:23:00  2016-02-08 15:23:00  29ca7f6f3e40ffec85bcf8f122bbe0f2bce4bf84ceac5fe327edb415b5de6660  52.8.228.23      pingly
2016-02-03 02:30:52  2016-02-03 02:30:52  27dd7a371d5f1bb82380d3d8f125dc6b6ce6686ef76ceaf653aa30a89ce30a76  54.153.123.93    pingly
2016-02-02 06:55:37  2016-02-03 02:30:52  765b84c4d6943d5bdce1344ae71a54693052e8c2d3c6dca5668cd8ac6915d768  52.8.228.23      pingly
2016-02-02 06:55:37  2016-02-02 06:55:37  76d13a7153f685daadfd953a5ad4f47182d370e9a6186d44e50c2f8c8699c7c5  54.153.123.93    pingly
2016-01-27 00:27:19  2016-01-27 00:27:19  d6268435f347f3659c62e4d3d593828168b4178634d77874a006128ecef8fd45  52.8.228.23      pingly
2016-01-27 00:27:19  2016-01-27 00:27:19  12418cebe4d678e9d7259d88df17d3b4b2399b688df625af8c36949beb7111db  54.153.123.93    pingly
2016-01-20 22:59:11  2016-01-20 22:59:11  ae006ac69262053858cfd6e53faf534357a6469d27c814a514dd23ce9e538b91  52.8.228.23      pingly
2016-01-20 22:59:11  2016-01-20 22:59:11  43b852e88c5b40fc1dab1f89879dea91151aad24499188f545dd66d91ded91ea  54.153.123.93    pingly
2016-01-12 15:21:48  2016-01-12 15:21:48  32400390eb1d18f8951a2628bb5d80cc841f2900b7d762de3375e7cce5718e3e  52.8.228.23      pingly
2016-01-11 09:55:19  2016-01-12 15:21:48  8429b6ad3089ee2d669522e2d6a7b32bb5491caf227752eb3e5162cf8178c909  54.153.123.93    pingly
2016-01-11 09:55:19  2016-01-11 09:55:19  d81eb0df7900752e4089c169929e3c4980c4541d62efa39771069e5b8a156faa  52.8.228.23      pingly
2016-01-07 23:13:57  2016-01-07 23:13:57  6da7234f950195aece486cb20983e5aa4b83ec165d38bb9a81cbe4a3eaca482b  54.153.123.93    pingly
2016-01-07 23:13:57  2016-01-07 23:13:57  68930a62b7ca8ebb64cdf3fb63225346df3d9b68d7209a64a1d99d867bfc8e72  52.8.228.23      pingly
2016-01-06 09:58:29  2016-01-06 09:58:29  45a40de2eb4fde5b0bd424b6972e24943a248e9a7d0150973ea8c228c14effad  54.153.123.93    pingly
2016-01-05 19:51:15  2016-01-06 09:58:29  e00508204335c1757054132c52420c67fd51307284de62516be03129ec98f5ed  52.8.228.23      pingly
2016-01-05 19:51:15  2016-01-05 19:51:15  c321a2a2212eeedfe151a67366870ad3c8f6c2cae9618d902f67282049a8cc93  54.153.123.93    pingly
2015-07-12 12:20:06  2015-12-30 10:08:15  d6bd3be49f3bf323cf17359ec4783840e8e185e1fae53deb783b8cf732c0c6f1  45.55.77.126     pingly
2015-06-02 08:54:22  2015-06-26 12:45:42  66cb7abdfe128d6f064e85874708bced957fadaaefea7d6c07861858fa2d77aa  104.131.121.205  pingly
2015-06-01 23:50:29  2015-06-02 00:05:52  ebf4eb4e43bfb21f695e45e6068b1b06f49414fadda6785c40b4555fd00e7c89  107.170.89.121   pingly
```

Am I crazy?  2 Character PR incoming...

**Comment by jakubd** [comment]
Actually not really sure what is happening here as I tried on another server (both running Ubuntu 12.04) and the issue doesn't crop up at all with the version from pip.

**Comment by passivetotal** [comment]
Hmm. I've gotten some strange responses with Ubuntu 12.04. We tested everything on 14 LTS. Can I close this for now and disregard the pull?

**Comment by jakubd** [comment]
Sounds good. Go right ahead.
