### ISSUE TITLE
pdns format not working in 'csv'

### ISSUE THREAD

**Issue by JonLittleIT** [passivetotal/python_api#17]
Jon_Little:ring Jon.Little$ pt-client pdns --query  www.ring.com --format 'csv'
Traceback (most recent call last):
  File "/usr/local/bin/pt-client", line 9, in <module>
    load_entry_point('passivetotal==1.0.23', 'console_scripts', 'pt-client')()
  File "/Library/Python/2.7/site-packages/passivetotal/cli/client.py", line 315, in main
    output = write_output(data, args)
  File "/Library/Python/2.7/site-packages/passivetotal/cli/client.py", line 170, in write_output
    data = [getattr(data, arguments.format)]
  File "/Library/Python/2.7/site-packages/passivetotal/libs/dns.py", line 211, in csv
    output += ', '.join(ordered) + "\n"
TypeError: sequence item 6: expected string or Unicode, list found
Jon_Little:ring Jon.Little$

**Comment by aeetos** [comment]
This was likely fixed in an earlier version and the issue never closed. I was unable to repro it in a current version; if the problem persists please re-open another issue.
