### ISSUE TITLE
`pt-client ssl` default template breaks on empty response

### ISSUE THREAD

**Issue by johannestaas** [passivetotal/python_api#8]
The default template that outputs `pt-client ssl` data breaks if the response is empty. `--format json` works, but default template breaks. 

```
$ pt-client ssl -q 192.65.247.107
Traceback (most recent call last):
 File "/usr/local/bin/pt-client", line 9, in <module>
   load_entry_point('passivetotal==1.0.18', 'console_scripts', 'pt-client')()
 File "/usr/local/lib/python2.7/dist-packages/passivetotal/cli/client.py", line 315, in main
   output = write_output(data, args)
 File "/usr/local/lib/python2.7/dist-packages/passivetotal/cli/client.py", line 189, in write_output
   data = [getattr(tmp, arguments.format)]
 File "/usr/local/lib/python2.7/dist-packages/passivetotal/libs/ssl.py", line 125, in text
   output += "[*] SHA-1: %s\n" % self.sha1
AttributeError: 'SslResponse' object has no attribute 'sha1'
```

**Comment by aeetos** [comment]
Formatters have been moved out of the codebase so this issue is no longer relevant. If you still see problems in a modern release let us know and we'll take a look.
