### ISSUE TITLE
ssl subcommand AttributeError: 'SslResponse' object has no attribute 'sha1'

### ISSUE THREAD

**Issue by dspruell** [passivetotal/python_api#9]
Unexpected exception from Python API client:

```
$ pt-client ssl -q 158.69.9.189
Traceback (most recent call last):
  File "/usr/local/bin/pt-client", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/passivetotal/cli/client.py", line 315, in main
    output = write_output(data, args)
  File "/usr/local/lib/python2.7/site-packages/passivetotal/cli/client.py", line 189, in write_output
    data = [getattr(tmp, arguments.format)]
  File "/usr/local/lib/python2.7/site-packages/passivetotal/libs/ssl.py", line 125, in text
    output += "[*] SHA-1: %s\n" % self.sha1
AttributeError: 'SslResponse' object has no attribute 'sha1'
```

**Comment by aeetos** [comment]
Closing old issue, no longer relevant to current codebase.
